module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'api-gateway',
        'svc-user-progression',
        'worker-game-loop',
        'svc-payment',
        'web',
        'desktop',
        'shared-types',
        'redis-client',
        'prisma',
        'eslint-config',
        'jest-config',
        'docker',
        'ci',
        'deps',
      ],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
  },
};
